### ISSUE TITLE
Only copy past and future arrays if necessary

### ISSUE THREAD

**Issue by KevinMusgrave** [charkour/zundo#111]
This: 

https://github.com/charkour/zundo/blob/1a171a44ab2cd16a3e0cf69a2868d7c265deb870/src/temporal.ts#L18-L20

could be changed to this:

```javascript
        if (get().pastStates.length) {
            const pastStates = get().pastStates.slice();
            const futureStates = get().futureStates.slice();
```

I'm guessing this could help slightly with performance.

**Comment by charkour** [comment]
Thank you. This was released in v2.0.0-beta.20
