### ISSUE TITLE
Optionally track state diffs (deltas)

### ISSUE THREAD

**Issue by KevinMusgrave** [charkour/zundo#113]
This is already in the road map, but I thought I'd create an issue for discussion.

I think this should be an option, like `trackDiffs: true`, because storing and applying diffs is more space-efficient but less time-efficient.

One possible library to use is: https://github.com/Starcounter-Jack/JSON-Patch

**Comment by charkour** [comment]
Thanks for starting the conversation!

I like your proposed API but let's talk through some potential options as well. Part of me is thinking we should allow the zundo used to pass in a function similar to `partialize` that is the diffing/patching function. That way the library doesn't need to bundle any sort of external dependency, and it gives the user the ability to use a function that compromises speed, memory, etc to fit their use case. 

Now I'm wondering if `partialize` supports patches by default. Would need to check the TS types but I'm thinking this might work in JS today. 

As for the specific library you shared, do you know if it supports Maps, Sets, and Dates? Or does it only support strings, numbers, arrays (serializable values)?

Thank you!

**Comment by KevinMusgrave** [comment]
I think your approach makes sense.

I believe JSON-Patch is meant for JSON, so no Maps, Sets etc.

[deep-object-diff](https://github.com/mattphillips/deep-object-diff) might be an alternative, but I don't think it comes with patching functionality.

**Comment by charkour** [comment]
I've added a draft PR to support `diff` to store state deltas.

**Comment by charkour** [comment]
This was released in `2.0.0-beta.25`. Thanks for the suggestion!
