### ISSUE TITLE
zundo@2.0.0-beta.20 gets resolved to zundo@2.0.0-experimental.0 in yarn berry

### ISSUE THREAD

**Issue by lordrip** [charkour/zundo#114]
First of all, thanks for this great library :muscle: 

#### Context
Currently, with the latest `dependabot` update of `zundo`, it seems that `zundo@2.0.0-beta.20` gets resolved to `zundo@2.0.0-experimental.0` in yarn berry.

It's very likely that this is happening because of the version defined with `^`.

If that's the case, please feel free to close this issue.

#### Screenshot of the resolution
![image](https://github.com/charkour/zundo/assets/16512618/b9c296a2-ede7-42e5-ad39-e0d5b3e797db)

#### Screenshot of the current versions on npm
![image](https://github.com/charkour/zundo/assets/16512618/662f0118-17ad-4eaa-9109-796d619375aa)

**Comment by charkour** [comment]
Hey, thank you for reporting the issue! Sorry that the wrong version is being resolved. 

In the past, using ^ worked for your team, right? I'm wondering if it's an issue with yarn berry. Perhaps you could try using ~ instead?

I hope to release version 2 soon, but I haven't written the v1 migration guide yet. 

Glad the package is helpful for you!

**Comment by charkour** [comment]
You could also specify `beta` or `latest` as the version. Not sure if it would know to update once v2 is released.

**Comment by lordrip** [comment]
Hi @charkour, thanks for the quick answer.

Yes, so far has been working fine with `^`, and the migration to `yarn berry` happened recently, so probably is that the cause.

In my case, in the meantime, I fixed it by specifying the version directly. I also wanted to take the opportunity to share this with other folks just in case someone experiences the same :smiley: .

If it helps, I could go back in git history, prior to the yarn berry migration to double check if this is coming from yarn berry.

As I said before, thanks for the amazing work, and no worries at all, please take your time for the v2 :muscle:

**Comment by lordrip** [comment]
Alright, I quickly checked and this seems to be from `yarn berry`. This is how it looks with `yarn@1.22.19`, the resolution went fine.

![image](https://github.com/charkour/zundo/assets/16512618/249f3476-e6c4-4ecb-95ff-a5c947b8d926)

That being said, I guess that this issue can be closed as this situation is not something that could be improved from the library side and there are workarounds available to circumvent the issue :smiley:.

On the bright side, this might serve as documentation for someone else that faces the same situation. According to the screenshot from the beginning, it seems that 41 folks (well, 40 if I subtract myself) have faced the same :sweat_smile:

**Comment by charkour** [comment]
Great, thank you for looking into it and confirming that it is an issue with `yarn berry`. Sorry it is causing an issue. 

I appreciate the support and thank you for using the library!
