### ISSUE TITLE
Does this work with deep nested objects?

### ISSUE THREAD

**Issue by cyango** [charkour/zundo#130]
I have a complex nested object i would like to use with zundo. Is it possible? if so what are the best practices?

**Comment by charkour** [comment]
Hi @cyango, yes this will work with deeply nested objects. Zundo stores the entire state object in its history. If you do any sort of diffing, you'll want to use something like [`fast-deep-equal`](https://github.com/epoberezkin/fast-deep-equal). 

When using deep objects with zustand, some people will use the [`immer` middleware](https://github.com/pmndrs/zustand#sick-of-reducers-and-changing-nested-states-use-immer) which can also work with `zundo`. I don't use `immer` but I know some people are fans.

Thank you!

**Comment by charkour** [comment]
My best advice is to "try it out" and see how using deep objects work!

**Comment by cyango** [comment]
Thanks for the quick answer. Actually i've tried it out already. 
I'm experiencing a issue that whenever my object is updated even if it has the same values (inside a deep nested array for example) it created multiple states that i need to click "Undo" a lot of time to get there.

I have tried equality: shallow, but with this it seems like it does not undo the wanted parts

**Comment by charkour** [comment]
Ah yes, you'll need to use a deep equality checker rather than `zustand/shallow`. If you share a code sandbox or stackblitz link, I can help further.

**Comment by charkour** [comment]
I can improve the docs to make that clearer (unless you'd like to make a PR)!

**Comment by cyango** [comment]
So i should use my own equality checker to check if a certain property or item on deep array is changing? How should i do this with the own state? I mean how do i pass the current state to the equality custom function?

**Comment by charkour** [comment]
HI @cyango,

Could you make a reproduction of the issue? Here is an example of using Deep Equal with zundo. Thanks!
