### ISSUE TITLE
When using the handleSet method to cooldown State pushes, diff gets the wrong pastState.

### ISSUE THREAD

**Issue by alexanderhorner** [charkour/zundo#132]
The pastState should be the last state actually pushed to the history (in other words, the last state handleSet was called on).

```javascript
diff: (pastState, currentState) => {
  const delta = diff(currentState, pastState);
  console.log('delta', delta)
  
  const newStateFromDiff = delta.reduce(
    (acc, difference) => {
      type Key = keyof typeof currentState
      if (difference.type === 'CHANGE') {
        const pathAsString = difference.path.join('.') as Key
        acc[pathAsString] = difference.value
      }
      return acc
    },
    {} as Partial<typeof currentState>,
  );
  return Object.keys(newStateFromDiff).length > 0 ? newStateFromDiff : null;
},
handleSet: (handleSet) => (state) => {
  if (!state) return

  debouncedHandleSetTimeoutID && clearTimeout(debouncedHandleSetTimeoutID)
  debouncedHandleSetTimeoutID = window.setTimeout(() => {
    handleSet(state)
  }, 300)
}

let debouncedHandleSetTimeoutID: number | null = null
```

**Comment by alexanderhorner** [comment]
The state that is passed to handleSet also should be the last actually saved history state. Else if you type 'A', wait a bit, and then type 'BCDE' real quick, the pastState will be 'ABCD'. It should be 'A' though.

**Comment by alexanderhorner** [comment]
Diff and equality does't make sense if the currentState isn't compared to the last state stored in history. Or am I missing something?

**Comment by charkour** [comment]
Hey @alexanderhorner, thanks for using zundo! Sorry for the issues. Could you make a reproduction in Code Sandbox of the issue you're seeing? 

Thanks

**Comment by alexanderhorner** [comment]
Sure. Before I do that, can you confirm that this is even an issue? Or is this how it's supposed to work?

**Comment by alexanderhorner** [comment]
Here is a Sandbox example: https://codesandbox.io/s/zundo-forked-233fhc?file=/src/App.tsx

The handleSet is debounced by 1 second. So if you wait more than 1 second between clicking increment, the history is 0, 1, 2, 3 like you expect. 

Now, if I click increment rapidly 5 times, the history should be [0] (with current state being 5). What actually happens is, that the history is [4]

**Comment by charkour** [comment]
Thanks for creating that! I appreciate the explanation which helps me to debug your issue.

To clear up confusion, based on your implementation, handleSet calls will be dropped, so there's no bug there. If you _expect_ all of the states to exist within the history then you should remove the debounce. If you need to debounce the handleSet calls for UI requirements, then we could either re-write your handleSet function or change how you're accessing the store.

Based on your explanation, the diff function is working properly. I think the best path forward is to either 1) remove the debounce method or 2) rewrite the handleSet function to not drop state changes.

Does this help?

**Comment by alexanderhorner** [comment]
The reason for dropping the handleSet calls is to debounce it, or in other words _to group together fast consecutive changes_.

Maybe it’s clear if I try to explain what I want to achieve. For example: let’s say I type A, wait 5 seconds, then type BCDE really quick. If I press undo now, I should get A, not ABCD. So state 1 is “A”, and state 2 is “ABCDE”, and the difference should be “add BCDE”.

The way I see it, this isn’t possible right now, because handleSet is called with prevState, which is (same for diff and equality) the last state a change was detected for, instead of the last state that was actually tracked and saved to the pastStates array. 

Unless I miss something, i would expect the diff and equality function to compare the current state to the last state in the pastStates array.

**Comment by alexanderhorner** [comment]
Hey, any update on this? I still think this doesn't make much sense as it currently works.

**Comment by charkour** [comment]
Hey @alexanderhorner,

Sorry this fell off my todo list. It doesn't totally make sense, but for now, I'd recommend removing the debounce from `handleSet`.

**Comment by alexanderhorner** [comment]
I need the denounce to group together changes that happen very quickly after one another. In my application I have a graph, and when I move a node in that graph, every pixel counts as a new state. Of course when I press undo, I just want it to go back to its last position where I started the drag from.

**Comment by charkour** [comment]
I'm finally getting around to this, sorry for the delay. 

I don't initially know what the expected behavior is here; but intuitively, I think it's working as expected, but I could very well be wrong.

**Comment by charkour** [comment]
Hi @alexanderhorner,

If you checkout this [CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zundo-forked-9yp7df?fontsize=14&hidenavigation=1&theme=dark), does this solve your problem? I think you were close to getting a working solution, but I added a package that made it easy to add debouncing and store the leading change.

**Comment by alexanderhorner** [comment]
Hello @charkour,
thanks for taking the time to make a demo. Unfortunately the CodeSanbox keeps refreshing in an infinite loop. 

I did implement a similar solution though (without extra packages, so a bit messier), and it seems to work great.

I actually thought about this solution before, but thought it wouldnt fix the issues I had with equality and diff. But it does. 

Thanks again for the help. Maybe update the cool down part of the documentation, if anyone else has a similar problem.

**Comment by charkour** [comment]
Hey @alexanderhorner, I'm glad that you found a solution!

I'll gladly improve the documentation. Could you point out what section specifically caused confusion? Thank you!

**Comment by charkour** [comment]
I've added this example to the docs in #148. Thanks for using zundo!

**Comment by alexanderhorner** [comment]
Thanks for making zundo!

**Comment by michaelabela** [comment]
hey @alexanderhorner what was your solution? I'm running into a similar issue. I have a set of points that I'm visualizing on a map and there's a marker draw mode where the user can quickly label dozens of points in a second or so. In the case that I have a map with 1 point, and then add 10 points in 1 second, I want undo to return the map to the state with just 1 point.

**Comment by alexanderhorner** [comment]
Hey man. The solution is storing the leading state (first state of the series) and saving that one the denounce timeout is reached.

Do you know what I mean? If not, I can try to find the piece of code for it tomorrow.
