### ISSUE TITLE
check if there are any undo steps

### ISSUE THREAD

**Issue by hsavit1** [charkour/zundo#181]
thanks for making this very useful lilbrary!

id like to disable my undo button if there are no undo operations to perform. similarly id like to disable the redo button if there are no futureStates. I think this would be a nice convenience method on the library to do this check

**Comment by charkour** [comment]
Thanks for the kind words!

You can disable undo button if there are no `pastStates` and disable the redo button if there are no `futureStates`.

https://github.com/charkour/zundo#going-back-in-time
