### ISSUE TITLE
Rename "clear" to "clearUndoHistory"

### ISSUE THREAD

**Issue by funwithtriangles** [charkour/zundo#24]
Having a top level function called `clear` is quite misleading. This doesn't look like it will clear undo history:

```javascript
useStore.getState().clear()
```

I think we should either rename `clear` to `clearUndoHistory` or move all of these helper functions into a top level object, `undoHelpers`. So the above would look like this:

```javascript
useStore.getState().undoHelpers.clear()
```

**Comment by charkour** [comment]
Yes. I like both suggestions, and I might lean towards the second suggestion. 

The original idea to keep things very terse (and potentially unclear) was the minimalist approach the @pmndrs team took with zustand.

**Comment by charkour** [comment]
But I'd much prefer making things more clear. Thanks for this great suggestion!

**Comment by charkour** [comment]
In v2, all utilities will be under a `temporal` object attached to the store. Thank you for the great suggestion! I preferred nesting objects to keep concise names.
