### ISSUE TITLE
Whitelist option (opposite of omit)

### ISSUE THREAD

**Issue by funwithtriangles** [charkour/zundo#26]
I'm not sure of the best naming convention but it would be good if we could have something like `whitelist`, which is an array of property names which are the only changes zundo should track. Basically, the opposite of the current `omit` option. My app has far more top-level properties I want to ignore so would be more convenient for me to explicitly name the few I actually want to track.

I'm happy to take this on but would be good to agree on naming. One option is to rename `omit` and have `whitelist` / `blacklist`.

**Comment by charkour** [comment]
I love the whitelist/blacklist naming. I thinking it would be part of the options that gets passed in when the undo store is created. 

Would it be possible to keep omit for now and have it be aliased? We can deprecate it but avoid breaking changes until we are ready for zundo v2.

**Comment by funwithtriangles** [comment]
All makes sense! An alias is a good idea for sure

**Comment by charkour** [comment]
This was released in [v1.5.9](https://www.npmjs.com/package/zundo/v/1.5.9)
