### ISSUE TITLE
[Help] How do I made `zundo` work with `subscribeWithSelector` in typescript?

### ISSUE THREAD

**Issue by tresabhi** [charkour/zundo#36]
How do I made `zundo` work with `subscribeWithSelector` in typescript?

Wrapping `subscribeWithSelector` with zundo middleware unleashes Pandora's box and it does not make sense to me, a relatively new typescipt-er.

I have tried extending `BlueprintStoreState` with zundo's `UndoState` (reference: https://github.com/charkour/zundo#alternatively-use-the-middleware), but that got me nowhere).

Current code:
```ts
interface BlueprintStoreState extends Blueprint {}

const blueprintStore = create<
  BlueprintStoreState,
  SetState<BlueprintStoreState>,
  GetState<BlueprintStoreState>,
  Mutate<
    StoreApi<BlueprintStoreState>,
    [['zustand/subscribeWithSelector', never]]
  >
>(
  subscribeWithSelector(() => blueprintTemplate),
);
```

**Comment by charkour** [comment]
Hey! Thanks for making this issue. 

To be honest, I haven't tried using zundo with `SubscribeWithSelector`. Would you be willing to provide a code sandbox with the issue you are seeing? That will help me debug the issue more quickly. Thanks!

**Comment by TresAbhi** [comment]
Wow, I made it work in the sandbox somehow; I surprise myself sometimes...

[https://codesandbox.io/s/angry-star-njtw0r](https://codesandbox.io/s/angry-star-njtw0r)

**Comment by TresAbhi** [comment]
I updated the sandbox to actually test the selector, and it is working flawlessly!

**Comment by charkour** [comment]
Thanks!! I'll update the docs tonight. Thanks for the example and for the updates!

**Comment by charkour** [comment]
Updated the [code sandbox](https://codesandbox.io/s/zundo-with-subscribe-with-selector-forked-mug69t?file=/src/App.tsx) for v2. Works!

Thanks for the initial implementation @tresabhi!
