### ISSUE TITLE
Support zustand v4

### ISSUE THREAD

**Issue by charkour** [charkour/zundo#38]

**Comment by charkour** [comment]
Right now, a workaround is the use `npm i --legacy-peer-deps`. 

I can update them by this weekend unless someone makes a PR before then. Thanks for your patience!

**Comment by charkour** [comment]
I'm also working on v2 and will release that last this month.

**Comment by Alexandredc** [comment]
Hi @charkour,
Thanks a lot for your work on this package ! I will be glad to give you some feedback when v2 released !
In the mean time, do you plan to publish a new beta version on npm in the next few days ?

**Comment by charkour** [comment]
Hi @Alexandredc!

I'll post an update to v1 tonight that supports zustand v4. And I'll release a beta of zundo v2 later this week which I would appreciate feedback on. Thanks for offering your help.

**Comment by charkour** [comment]
Hey @Alexandredc and all, 

[v1.6.0](https://www.npmjs.com/package/zundo/v/1.6.0) now supports zustand v4. It's not the prettiest code, but it is compatible. Please let me know if there are any issues. 

As of now, all new features requests will be directed to [v2](https://github.com/charkour/zundo/tree/v2)
