### ISSUE TITLE
Improve types (chaining middlewares)

### ISSUE THREAD

**Issue by funwithtriangles** [charkour/zundo#42]
While this lib is now working with zustand v4, the types still aren't quite right when chaining with other middlewares. I'm currently in the middle of trying to fix this, [ following this guide](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md#middleware-that-changes-the-store-type).

Hopefully I can get a PR in soon!

**Comment by charkour** [comment]
Thanks, @funwithtriangles!

I'll review it once you make that PR. I apologize that the latest release wasn't the most type-correct code so I appreciate your help.

**Comment by charkour** [comment]
This has been released as [v2.0.0-experimental.0](https://www.npmjs.com/package/zundo/v/2.0.0-experimental.0). 

You can install with npm i zundo@experimental. 

Please re-open if this issue is not solved! Thanks.
