### ISSUE TITLE
Combine zundo middleware with immer & devtools

### ISSUE THREAD

**Issue by mowhcen** [charkour/zundo#49]
recently, I work on a project that uses [zustand](https://github.com/pmndrs/zustand) store as its state manager.

- I have nested states so have to use [immer middleware](https://github.com/pmndrs/zustand#immer-middleware)
- And I use typescript so for debugging I needed [redux devtools](https://github.com/pmndrs/zustand#typescript-usage)

so I want to add undo & redo feature for my store but here is the problem :

![image](https://user-images.githubusercontent.com/60854757/190403228-db1708a6-0517-43d3-a6a4-604f55b28c87.png)

This my imports 
`import create from "zustand";`
`import { immer } from "zustand/middleware/immer";`
`import { devtools } from "zustand/middleware";`
`import { UndoState ,undoMiddleware} from "zundo";`

store type: `export interface BookBuilderStore extends UndoState { . . . }`

**Comment by mowhcen** [comment]
zundo version ` "zundo": "^1.6.0"`

And this sandbox shows a simple version of my store: [sandbox](https://codesandbox.io/s/currying-dream-8o16to?file=/src/store.ts)

**Comment by charkour** [comment]
Great, thanks! There's another open issue with that version. I think the types are a bit buggy. 

After my work day, I can try to play around with it. 

You can try running `npm i zundo@experimental`. That version of the package may have fixed those type issues.

**Comment by mowhcen** [comment]
I used the experimental version and the current error is gone but now i can't undo or redo states  and because types are required i have to define the functions in store and basically it is just a function and don't do anything so i made them optional and i got the same result

**Comment by charkour** [comment]
Thanks for the feedback. Sorry for the issues!

I can look into this more later.

**Comment by mowhcen** [comment]
I saw this release note and test it and everything is working now except for some nested changes in state  :) 
` const { undo, redo, clear, setIsUndoHistoryEnabled, getState } = useStore.temporal;`

tank you for your help 

this is my solution: 
[sandbox code](https://codesandbox.io/s/currying-dream-8o16to?file=/src/app.tsx)

**Comment by charkour** [comment]
@mowhcen glad it sounds like it is working. Is there anything else I can help you with? I'll release v2 beta this weekend.

**Comment by mowhcen** [comment]
sounds great i will look into it 😄

**Comment by charkour** [comment]
Hey @mowhcen,

I've released a beta version of zundo. You can install it with `npm i zundo@beta`. Please reopen the issue if you run into problems. Thanks for your patience!
