### ISSUE TITLE
clear undo history / exclude changes

### ISSUE THREAD

**Issue by MaxTwentythree** [charkour/zundo#5]
Hi there,
I checked out zundo and I'm already super happy with it, it works pretty much out of the box for me, so yay!

However, I have 2 usecases that I can't get to run right now:
1) clear undo history: 
After persisting changes made to objects in my zustand-store to the database, i would like to clear the undo history (so that the undo list is empty) .. is this possible?
2) exclude changes:
Some changes to the objects in the store I'd like to exclude from being undoable .. is there some kind of filter functionality? Or should I better create a separate store where all my undoable objects live?

I am aware that zundo is still very new, but I thought I would ask if there are any plans in this regard.
Thanks in advance!

**Comment by charkour** [comment]
Hi @MaxTwentythree,

Thanks for the notes. I'm glad to hear using it has been going well for the most part. 

1. clear undo history:
This is a good idea! This isn't (easily) possible now, but would it be useful to have `useUndo()` return a `clear` function that can be called to clear to past states? `const { undo, redo, clear } = useUndo()`

2. exclude changes:
I haven't thought about this before, and I don't think it is possible to be done currently with zundo. So if your store contained bears and honey, are you wanting to allow bears to be undoable and honey not to be undoable? This one would be trickier to implement, but it could be done. For now, I would just have two separate stores. One where undoable objects live and the other where they cannot be undone. 

Thanks!

**Comment by MaxTwentythree** [comment]
@charkour 
Thanks for your reply!
concerning the clear function: this would be awesome!

No worries concerning 2) I'll create a separate undo store :)

**Comment by charkour** [comment]
Sweet, I can add the `clear` function later (in about 10 hours) unless you would like to add it yourself and make a PR.

For question/request 2, if this feature needs to be reconsidered in the future, please feel free to make a new issue! Thanks

**Comment by MaxTwentythree** [comment]
I would be super grateful for the function! I can try to create a PR, but probably would not make it until the weekend, so probably you're faster..

**Comment by charkour** [comment]
The `clear` function was published in [v0.4.0](https://www.npmjs.com/package/zundo/v/0.4.0). Let me know if you have any troubles!

If it works well, then you can close the issue. Thanks!

**Comment by MaxTwentythree** [comment]
This works perfectly! Thanks a lot for the quick enhancement!!

**Comment by charkour** [comment]
The second enhancement to exclude changes is tracked in #8 and is implemented in #10.
