### ISSUE TITLE
"npm -i zundo" fails

### ISSUE THREAD

**Issue by ohthepain** [charkour/zundo#50]
Same results with "npm -i zundo@beta"

It seems to be requiring zustand 3.0.0. I am on zustand 4.1.1. 

zundo depends on zustand 4.1.1 here: https://codesandbox.io/s/zundo-2dom9?file=/src/App.tsx:27-31

master* $ npm i zundo                                                                                                      [9:46:00]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: powermad@0.1.0
npm ERR! Found: zustand@4.1.1
npm ERR! node_modules/zustand
npm ERR!   zustand@"^4.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zustand@"^3.0.0" from zundo@2.0.0-beta.3
npm ERR! node_modules/zundo
npm ERR!   zundo@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by ohthepain** [comment]
I confirmed in a new project. `npm I undo` works as long as I have not installed `zustand`

**Comment by charkour** [comment]
Oops, thanks an issue! I should be able to get that fixed soon. 

Thanks for reporting!

**Comment by charkour** [comment]
This should be fixed. 

`npm i zundo@beta` should update you to beta.4

Please let me know if you have any issues.
