### ISSUE TITLE
Log : type & payload

### ISSUE THREAD

**Issue by stephanepx** [charkour/zundo#57]
Hi !
Thank's for all your work !
I've installed the library on my project, and now logs are not displayed in devtools
In my setters I have something like this : 

```typescript
updateField: payload => 
  set(
      state => {
        const { value } = payload;
        state.value = value
      },
      false,
      log('updateField', payload),
    ),
```

Without Zundo, my logs are correctly displayed in devtools.
With Zundo, all functions in devtools are "anonymous"

Do you have an idea ?

Thank's!

**Comment by charkour** [comment]
Hey @stephanepx,

Thank you for using zundo and I'm sorry to hear you are having trouble. Happy to help.

To help me debug the issue, what version of zustand and zundo are you using? Also, in what order are you adding your temporal and devtools middleware?

Could you provide a code sandbox with the issue? Here is a [starter](https://codesandbox.io/s/zundo-2dom9).

**Comment by magicspon** [comment]
@stephanepx i resolved this issue by reordering the middleware.

```
	return createStore<TBuilder>()(
		persist(
			temporal(
				devtools(
```

**Comment by stephanepx** [comment]
Thank's @magicspon !!
@charkour I think you can close it ! :) 
Thank's again for this lib !

**Comment by charkour** [comment]
Thanks for the update! Cheers
