### ISSUE TITLE
zundo@2.0.0-beta.8 incompatible with zustand@v4.3.x

### ISSUE THREAD

**Issue by BrunnerLivio** [charkour/zundo#62]
## Reproduction / Severity

At the moment, when you install `zundo@2.0.0-beta.8` and have the following in your package.json:

```json
"zustand": "^4.0.0"
```

Then Zustand will automatically update to [`4.3.1`](https://www.npmjs.com/package/zustand?activeTab=versions) (because of the caret `^`), resulting in this error:

```
TypeError: (0 , import_vanilla.default) is not a function
index.js?46cb:334 Uncaught TypeError: (0 , import_vanilla.default) is not a function
    at createVanillaTemporal (file:///..../node_modules/zundo/dist/index.js:46:37)
```

## Workaround

I figured out that only **zustand `v4.3.0`/`v4.3.1`** is causing this issue. Downgrading to `npm install zustand@4.2.0` will work as expected.

## Debugging

When exploring the compiled `node_modules/zundo/dist/index.js` file I `console.log` the import statement of `zustand/vanilla`:

```javascript
[...]

// src/temporal.ts
var import_vanilla = __toESM(require("zustand/vanilla"));
console.log(import_vanilla)

var createVanillaTemporal = (userSet, userGet, baseOptions) => {
[...]
```

Which prints the following output:

```
{
  default: {
    createStore: [Function: createStore],
    default: [Function: vanilla]
  },
  createStore: [Getter]
}
```

**Comment by charkour** [comment]
Thanks for reporting! 

I didn't expect a breaking change from zustand, but they have appeared to do so. If you want, can you make a PR to update the peer dependency?

I'll see about making zundo compatible with the lastest version of zustand.

**Comment by charkour** [comment]
I was able to reproduce the issue locally. It seems to look like they've removed one of the imports we depended on in the middleware.

**Comment by charkour** [comment]
Thanks for the fix! It is live. You can use `npm i zundo@latest`
