### ISSUE TITLE
handleSet need to know it's from undo and not use debounce.

### ISSUE THREAD

**Issue by pissang** [charkour/zundo#71]
Adding debounce in the `handleSet` method makes it easy to filter the frequent changes. Like dragging the cube, tweaking color, etc. But I found when I long pressing `ctrl+z` to `undo` the bunch of operations. It will also call `handleSet` and being debounced, which will loose lot's of histories when `redo` again. It will be great if there is a way to know if the change is from `undo` and not calling the `debounce` method.

**Comment by charkour** [comment]
Hi @pissang,

Thanks for the report. I think I understand your problem. You'd like different behaviors when setting state via the main store vs undo/redo changing the temporal state?

**Comment by pissang** [comment]
Hi @charkour 

> You'd like different behaviors when setting state via the main store vs undo/redo changing the temporal state?

Yes, or something like `coolOffDurationMs` in v1.6.0 ?

**Comment by charkour** [comment]
Thanks! The `handleSet` option in v2 should allow for the user to define that. I like your original idea to know if the change in from `undo`/`redo` rather than a tracked state changed in the original store.

**Comment by charkour** [comment]
@pissang, would you be willing to create an example of your current app? I would like to add this feature. Thanks!

**Comment by charkour** [comment]
@pissang,

`handleSet` is only called when called the setter in the main store. Calling `undo` or `redo` will not be throttled. I've tested this back as far as `v2.0.0-beta.11`. Sorry for any confusion this may have caused. Do you have ideas on how we can improve the documentation?

here is a demo:
https://codesandbox.io/s/zundo-handleset-debounce-nq7ml7?file=/src/App.tsx
