### ISSUE TITLE
Batch specific updates for undo/redo?

### ISSUE THREAD

**Issue by KrisLau** [charkour/zundo#74]
So I have a rather large/complicated store for baseball scoring which has a bunch of actions that could happen. I have some that are just incrementing the ball count where i would like undo to just decrement the ball count by one. Then there are other actions where I change like 4 states, trigger a 1s long animation, then change more states which I would like to be batched into one update for the undo. 

Is there a way I can set a flag for the start of sth like a transaction? that way zundo knows that all of those changes should be considered one change.

**Comment by charkour** [comment]
Hi @KrisLau,

Thanks for your question. Right now, zundo doesn't support that natively, but you could define a [`handleSet` function](https://github.com/charkour/zundo#cool-off-period) to batch incoming changes. In this function, you would need to have a value in memory to track the batch of incoming changes, and then after a certain period, call `handleSet`.

**Comment by KrisLau** [comment]
@charkour Would I be able to request that as a new feature? I don't have the skills to implement it myself but I was wondering if maybe something like this would work:

In the temporal `options`, there would be a `enableBatching` or sth like that that would accept a boolean. Then they would need to add a state like `_transaction` or `_transactionGroup` which would accept a string. If the first update they make to the store is:
```js
{
   _transaction: 'deposit', 
   count: state.count + 1
}
```
If the subsequent update has the `_transaction` value of `'deposit'` still zundo would batch that update together with the previous one (replace the latest entry in `pastStates` with the current one). However if `_transaction` had a different value, zundo would treat it like a new entry to the `pastStates`.

**Comment by KrisLau** [comment]
@charkour ?

**Comment by KrisLau** [comment]
@charkour ?

**Comment by charkour** [comment]
Hey thanks, sorry @KrisLau, work has been busy. 

I really like your idea, and I think if you use a custom `handleSet` function, you should be able to batch updates. However, if every update includes updates to every field in the state, you can simply add `throttle` or `debounce` from a utility library to effectively batch updates. Using one of those methods will "drop" intermediate state changes and only save changes on a specific time interval.

**Comment by KrisLau** [comment]
@charkour No worries, I always appreciate you taking the time to reply! I think I managed to figure it out using `handleSet`! I created a state called `batchWithPrevious` and if it's true, I skip over calling `handleSet`

**Comment by charkour** [comment]
Glad you figured it out! And thanks for the update. 

You're also welcome to create a PR to make batching easier or to add an example of it! Thank you :)

**Comment by KrisLau** [comment]
Will do! I'll probably add an example for now and then work on adding a PR later because I'm in the middle of preparing for our app's launch right now hahaha

**Comment by charkour** [comment]
For sure! If the app is public, I would love to see it once it is launched.

**Comment by KrisLau** [comment]
Cool, I'll drop a link to it here once it is launched! Date for launch is up in the air right now haha
