### ISSUE TITLE
Initialize / load existing `pastStates`

### ISSUE THREAD

**Issue by KrisLau** [charkour/zundo#75]
So I'm using zundo to add undo/redo functionality to my app but each instance of a sports game has its own state history that I need to be able to undo/redo. Is there a way i can save the `pastStates` and `futureStates` to my db and load those back into zundo?

**Comment by charkour** [comment]
It's not currently possible, but I love that idea!

Thank you for the suggestion!

**Comment by charkour** [comment]
Technically, you should be able to achieve this by using `useMyStore.temporal.setState({ pastStates: statesFromDb.past, futureStates: statesFromDb.future })`

**Comment by KrisLau** [comment]
@charkour That worked, thanks so much! If you get time, I might have an enhancement suggestion here: https://github.com/charkour/zundo/issues/74#issuecomment-1462189793

**Comment by charkour** [comment]
Hey @KrisLau,

You can now initialize the temporal store with past and future states as of `v2.0.0-beta.15`. Please let me know if it works for you. Thanks!

**Comment by KrisLau** [comment]
@charkour Unfortunately for my use case I can't initializing the past and future states since the user has to select the team and  game then I programmatically load a bunch of info into the store from the database! However I just realized that `useMyStore.temporal.setState({ pastStates: statesFromDb.past, futureStates: statesFromDb.future })` doesn't work for the future states for some reason

**Comment by charkour** [comment]
Gotcha, are you using React? If so, you can use React context to initialize your zustand store after the user selects the state!

**Comment by KrisLau** [comment]
I'm using React Native and yeah that's kind of similar to what I'm doing currently! The only difference is I have 2 contexts for the game. Also just realized the state is being applied but `futureStates` is being wiped when I move to the next screen

**Comment by KrisLau** [comment]
@charkour I'm using React Native and yeah that's kind of similar to what I'm doing currently! The only difference is I have 2 contexts for the game because one depends on the value of another.

Also just realized the state is being applied with the `setState` but `futureStates` is being wiped when I move to the next screen, really weird since `pastStates` is fine. Not sure why?

**Comment by charkour** [comment]
Gotcha, are you using this [zustand dependency injection pattern](https://github.com/pmndrs/zustand/blob/main/docs/guides/initialize-state-with-props.md) with the new [zundo API for initializing history](https://github.com/charkour/zundo#initialize-temporal-store-with-past-and-future-states)? Using these two together should allow you to achieve your desired behavior and you should no longer be needing to call `useMyStore.temporal.setState({ pastStates: statesFromDb.past, futureStates: statesFromDb.future })`

**Comment by charkour** [comment]
For zustand dependency injection, I made a simple helper https://github.com/charkour/zustand-di
