### ISSUE TITLE
futureStates is not getting populated

### ISSUE THREAD

**Issue by krokben** [charkour/zundo#87]
Hi, unfortunately, whenever I trigger `undo()`, the `futureStates` array doesn't fill up with any states. It's always an empty array. Have I misunderstood how it works or is this a bug?

I will try to explain my setup here:

```
const useProjectStateStore = create()(
  devtools(
    temporal(
      (set, get) => ({...}),
      { equality: shallow, limit: 100 }
    )
  )
)
```

I then run this:

```
useProjectStateStore.temporal.getState().undo();
```

**Comment by charkour** [comment]
Hi @krokben,

Thank you for submitting an issue. Could you provide a reproduction Code Sandbox with the issue?

**Comment by charkour** [comment]
Thanks for the update!
