### ISSUE TITLE
 Uncaught TypeError: Cannot read properties of undefined (reading 'subscribe') 

### ISSUE THREAD

**Issue by vaynevayne** [charkour/zundo#92]
How do I work with context?

i have a sample demo, but it not  work, please help me look at ,thanks 

https://stackblitz.com/edit/react-ts-fmst33?file=Child.tsx

or
https://codesandbox.io/p/sandbox/react-vite-ts-9qputt

or
https://stackblitz.com/edit/vitejs-vite-dsvpc4?file=src/store.tsx

**Comment by vaynevayne** [comment]
brother  If has way to resolve it?

**Comment by charkour** [comment]
HI @vaynevayne,

Thank you for your message. Here is the [zustand documentation](https://github.com/pmndrs/zustand#react-context) for working with context. Does this answer your question? 

Thanks

**Comment by vaynevayne** [comment]
It's been a long time
Didn't you read the link again? What do you think is the inconsistency between my code and the context usage on its official website? 
@charkour 
You go in and have a look at the link, remove your zundo, the function is normal, plus you will report an error, can you be more serious?

**Comment by charkour** [comment]
Hi @vaynevayne,

I looked at the example, but found out that [zustand v4 does not work with stackblitz](https://github.com/stackblitz/core/issues/1852). Can you please make a [codesandbox](https://codesandbox.io/) with your code? 

Thank you

**Comment by vaynevayne** [comment]
hello, @charkour    this codesand : 

https://codesandbox.io/p/sandbox/agitated-monad-khz4y4?file=%2Fsrc%2Fstore.tsx

**Comment by vaynevayne** [comment]
I'm sorry. I feel like I may have written the code wrong. can you correct it for me?
@charkour 
<img width="1144" alt="image" src="https://github.com/charkour/zundo/assets/124666577/39fe1827-aa10-4268-b147-e37e0880073c">

**Comment by charkour** [comment]
Thanks for the reproduction!

Does this solve your issue?

```tsx
export const useTemporalStore = <T extends unknown>(
  selector: (state: TemporalState<State & Actions>) => T,
  equality?: (a: T, b: T) => boolean
) => {
  const store = useContext(BearContext);
  if (!store) throw new Error("Missing BearContext.Provider in the tree");
  useStore(store.temporal, selector, equality);
};
```

Link to [Code Sandbox](https://codesandbox.io/p/sandbox/zundo-w-context-53i4wn)

**Comment by vaynevayne** [comment]
Thank you. This works. I'd like to ask again that I have a deep object in my store. I want his width property not to be added to the undo redo. How should I do this?

```jsx
const tableColumnManage ={
name:{
 visible:true,
width:100,

},
age:{
 visible:true,
width:100,
}
}
```
